name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore DentalMVP.csproj
      - name: Build (Release)
        run: dotnet build DentalMVP.csproj -c Release --no-restore
